In [38]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (ConfusionMatrixDisplay, accuracy_score,
                             classification_report, confusion_matrix, f1_score,
                             precision_score, recall_score,
                             roc_auc_score)
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
lb = LabelEncoder()

import pickle

In [39]:
df = pd.read_csv('data/data.csv')
df.head()

URL  Company           Type Visited
0  https://www.youtube.com/watch?v=khCziHJQSwg  Youtube  Entertainment     Yes
1  https://www.youtube.com/watch?v=SA7AIQw-7Ms  Youtube  Entertainment     Yes
2  https://www.youtube.com/watch?v=AG-erEMhumc  Youtube  Entertainment     Yes
3  https://www.youtube.com/watch?v=JGulAZnnTKA  Youtube  Entertainment     Yes
4  https://www.youtube.com/watch?v=B7BmScPcNms  Youtube  Entertainment     Yes

In [40]:
df.shape

(24, 4)

In [41]:
x = df.iloc[:, 1:3]
y = df.iloc[:, 3]

In [42]:
x=pd.get_dummies(data = x, drop_first=True)
x.head()

Company_W3Schools  Company_Youtube  Type_Entertainment
0              False             True                True
1              False             True                True
2              False             True                True
3              False             True                True
4              False             True                True

In [43]:
y = lb.fit_transform(y)
y[:10]

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0])

In [44]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=123, test_size = 0.2) 

In [45]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
y_pred = dt.predict(x_test)

confusion_matrix(y_pred, y_test)

array([[0, 2],
       [1, 2]], dtype=int64)

In [46]:
dt.predict_proba(x_test)

array([[0.2, 0.8],
       [1. , 0. ],
       [1. , 0. ],
       [0.2, 0.8],
       [0.2, 0.8]])

In [47]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.67      0.50      0.57         4

    accuracy                           0.40         5
   macro avg       0.33      0.25      0.29         5
weighted avg       0.53      0.40      0.46         5



In [50]:
# with open('models/DecisionTree.pkl', 'wb') as f:
#     pickle.dump(dt, f)